# config/meta.yml

meta_product_name: "InstaItinerary - Customize Your Day"
meta_title: "InstaItinerary - Customize Your Day"
meta_description: "Select by category and amount of available time"
meta_image: "https://res.cloudinary.com/dh2tpkp5c/image/upload/v1559726681/insta-itinerary-cover_nwp6co.png"
